version: '3.8'

name: nestjsprisma

services:
  postgres-db:
    image: postgres:latest
    ports:
      - 5434:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123
      POSTGRES_DB: nest
networks:
  nestjs:
