version: '3.8'

name: headless_cms

services:

  frontend:
    build:
      context: ../frontend
      dockerfile: ../dev-config/Dockerfile.frontend
    ports:
      - 3000:3000
    environment:
      CMS_TOKEN: ${CMS_TOKEN}
      CMS_URL: ${CMS_URL}
    volumes:
      -  ../frontend:/usr/app
    networks:
      - strapi

  strapi:
    build:
      context: ../cms
      dockerfile: ../dev-config/Dockerfile.cms
    ports:
      - 1337:1337 
    environment:
      APP_KEYS: ${APP_KEYS}
      API_TOKEN_SALT: ${APP_KEYS}
      ADMIN_JWT_SECRET: ${ADMIN_JWT_SECRET}
      TRANSFER_TOKEN_SALT: ${TRANSFER_TOKEN_SALT}
      DATABASE_HOST: db
      DATABASE_PORT: ${DATABASE_PORT}
      DATABASE_NAME: ${DATABASE_NAME}
      DATABASE_USERNAME: ${DATABASE_USERNAME}
      DATABASE_PASSWORD: ${DATABASE_PASSWORD}
    # volumes:
    #   -  ../cms:/usr/app
    networks:
      - strapi

  db:
    image: postgres
    restart: always
    ports:
      - 5432:5432 
    environment:
      POSTGRES_USER: ${DATABASE_USERNAME}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
      POSTGRES_DB: ${DATABASE_NAME}
    volumes:
      - db:/var/lib/postgresql/data
    networks:
      - strapi

networks:
  strapi:
volumes:
  db:
